version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins-docker
    build:
      context: .
    ports:
      - "8080:8080"
    # We are using this volume to prevent docker from deleting our jenkins data each time we restart the container
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
